### ISSUE TITLE
Application mi remote

### ISSUE THREAD

**Issue by yohpagan** [MiFrance/miui-xml-V7-FRENCH#13]
Bonjour je possède un Mi 4s sous la dernière stable 7.3.1.
Mi remote n'est pas traduite. Une partie est en chinois, l'autre en anglais.
Se serait sympa de résoudre ceci.
Merci

**Comment by gferry** [comment]
Bonjour,

Est-ce que tu peux faire un sujet là-dessus sur le forum MiFrance, si ce n'est pas déjà fait ?
Merci !

**Comment by yohpagan** [comment]
Pas de soucis.

Je poste ça dans la journée.

Tchuss et merci pour votre boulot.
