### ISSUE TITLE
Mode d'installation dans le readme

### ISSUE THREAD

**Issue by nodje** [MiFrance/miui-xml-V7-FRENCH#14]
salut,

ce serait sympa d'expliquer en qq lignes comment faire pour installer la trad.
Ca doit pas être bien difficile mais ne l'ayant jamais fait je n'ai vraiment aucune idée de par où commencer...

merci d'avance

**Comment by gferry** [comment]
Hello,

Le problème c'est que nous n'installons pas les traductions : nous faisons seulement les modifications dans les fichiers au fil de l'eau, et chaque semaine, une autre équipe les récupère automatiquement pour générer les nouveaux APKs.

Après, peut-être n'ai je pas bien compris ta question ? :)

**Comment by nodje** [comment]
ok, non c'est moi qui n'ait pas très bien compris le fonctionnement de ce repo.
Donc en fait cette trad est intégrée directement au ROM qui sont en téléchargement sur le site mifrance c'est bien ça?

Donc en gros y a pas moyen de juste installer des fichiers langues, il faut reinstaller toute la ROM?

**Comment by gferry** [comment]
Yep, c'est bien ça : après, il doit être possible, avec un peu d'huile de coude, de recompiler des APKs avec des traductions modifiées -> mais c'est une autre histoire :)
