### ISSUE TITLE
Erreur de traduction

### ISSUE THREAD

**Issue by Ro9eR78180** [MiFrance/miui-xml-V7-FRENCH#15]
Bonjour,

Il y'a une petite erreur de traducton : dans les contact, losque l'on fait un appuie long sur un contact , tout en bas il y'a marqué "Nouveau" alors que ça devrait être "Ajouter au favoris"
Lorsque l'on fait un appuie long sur un contact favoris, il y'a bien la fonctione "Enlever des favoris"

**Comment by manzing** [comment]
Bonjour,
J'ai corrigé l'erreur dans un fork, reste aux personnes autorisées à fusionner.
