### ISSUE TITLE
fc Settings/Additional/Buttons french paramètres/paramètres additionnels/touches

### ISSUE THREAD

**Issue by vince68** [MiFrance/miui-xml-V7-FRENCH#18]
fc in the menu Settings/Additional/Buttons, if I change the language to english no problem. Present on rom xiaomi.eu_multi_MI4c_6.9.8_v8-5.1.zip

**Comment by Uliaoth** [comment]
exact same problem on Mi5 with the rom **xiaomi.eu_multi_MI5_6.9.15_v8-6.0.zip** 

English is ok, but crash with french.
