### ISSUE TITLE
Quelques erreurs de traduction

### ISSUE THREAD

**Issue by owavreille** [MiFrance/miui-xml-V7-FRENCH#3]
Bonjour,
Quelques erreurs retrouvées dans la dernière version : 
- Dans contact : 
  Il manque le "ici" dans "Appuyez ici pour afficher la photo du profil du contact"
- "Pas de notification" sans "s" à notification
- À la première ouverture de météo "Allow" et "Exit" non traduit pour autoriser la localisation gps
- les exemples de notes sont en doublon, en anglais et en français
- Nouvelles notes et supprimer sont superposés
  Merci pour la traduction !

**Comment by MiFrance** [comment]
On regarde ça au plus vite, merci !

**Comment by owavreille** [comment]
Ok, très bien. 
Autre élément : les raccourcis du lecteur musical ne sont pas traduits dans la barre d'état.
"Open music player" et "No music".

**Comment by Gaubry31** [comment]
Bonjour,

Dans Paramètres, puis Ne Pas Déranger, rien n'est traduit dans ce menu.

Dans Paramètres puis Paramètres applications système, l'icones "Paramètres" est mal tradui car ça correction au paramétrage du calendrier. il faudrait peut etre mieux qu'elle se nomme "Calendrier".

Merci pour la Trad de la Rom en tout cas ^^

**Comment by gferry** [comment]
Hello,

Est-ce que tu rencontres encore des erreurs de traduction, ici et là ?
Sinon, on peut fermer cette issue

**Comment by owavreille** [comment]
Bonjour
Il reste encore quelques petites corrections à faire :
Dans la gallerie photos, les menus concernant l'identication des personnes n'est pas traduit.
Il y a toujours un s à notification dans le menu supérieur...
Merci

**Comment by gferry** [comment]
Quel est ton téléphone ? Un Mi3 ? Un Note ?

**Comment by owavreille** [comment]
Un mi4i ...

**Comment by gferry** [comment]
Ok, du coup c'est normal : actuellement nous utilisons comme base les fichiers de traduction du Mi3. Une grande partie des textes sont communs à tous les appareils, mais il y a de légères différences... On va trouver une solution pour harmoniser tout ça rapidement (j'espère)

**Comment by ghost** [comment]
Salut owavreille, j'ai jeter un œil vite fait là et ça devrait être traduit pourtant (dans la galerie) tu as quelle numéro de version de rom ?

**Comment by owavreille** [comment]
La 5.10.22, la partie non traduite est le menu d'aide d'identification des personnes, au premier lancement.
