### ISSUE TITLE
Signaler numéro tél comme spam

### ISSUE THREAD

**Issue by actupsp** [MiFrance/miui-xml-V7-FRENCH#4]
Salut,

Le menu de signalement de spam n'est pas traduit dans la 5.10.16 et donc surement dans les anciennes aussi.
Quand on clic sur un numero puis signaler comme spam, on a le choix entre "harassment", "sales/ads", "real estate agent", "express & delivery" et "scam"

Merci
Damien

**Comment by gferry** [comment]
Effectivement, je vais tâcher de corriger ça pour la mise à jour de cette semaine.
Merci !
