### ISSUE TITLE
Modification du fond d'écran du lockscreen

### ISSUE THREAD

**Issue by MisterBeee** [MiFrance/miui-xml-V7-FRENCH#5]
Bonjour,

Je ne sais pas si je suis au bon endroit, mais j'ai rencontré des problèmes avec l'application "Thèmes" pour changer le fond d'écran du lockscreen. J'étais obligé de passer mon téléphone en anglais pour pouvoir accèder aux options de customisation dans l'application "Thèmes". Maintenant que je suis repassé en francais, je n'ai à nouveau plus accès, mais il m'a gardé les modifications que j'ai faites lorsque je l'avais mis en anglais.

Merci!

**Comment by gferry** [comment]
L'appli Thèmes est un peu bancale depuis quelques semaines, car Xiaomi vient de sortir une version globale officielle de MIUI7, dans laquelle le menu de personnalisation est masqué par un menu simplifié "Wallpaper". Je pense que tout cela va se normaliser prochainement.

**Comment by MisterBeee** [comment]
Merci beaucoup!

---

Michael Pillonel
Imp. de la Forêt 6
1782 Lossy
+41 78 618 17 59

## michael.pillonel@gmail.com
