### ISSUE TITLE
Menu tout en chinois

### ISSUE THREAD

**Issue by actupsp** [MiFrance/miui-xml-V7-FRENCH#6]
Salut

il y a un probleme de trad dans la 5.11.12
dans parametres - parametres additionnels - batterie & performance - gérer l'utilisation de la batterie par les applis
dans ce menu il y a du chinois donc impossible de savoir a quoi correspond les réglages

merci
Damien

**Comment by gferry** [comment]
Hello,

J'ai pu oublier quelque chose... quel téléphone ?

**Comment by actupsp** [comment]
salut

sur le redmi note 2

**Comment by gferry** [comment]
Ok, je vais regarder ça pour la prochaine mise à jour !
Merci du retour
