### ISSUE TITLE
Compatibilité Redmi Note 3 ?

### ISSUE THREAD

**Issue by rroblik** [MiFrance/miui-xml-V7-FRENCH#7]
Bonjour,

Peux-être en savez-vous plus sur la compatibilité de la rom FR (ou multi) avec avec le dernier Redmi Note 3 ?

Merci d'avance.

**Comment by gferry** [comment]
Bonjour,

Pour le moment, il me semble que la multi (venant de xiaomi.eu) ne supporte pas le dernier Redmi Note3. En revanche, peut-être que la ROM globale officielle (équivalent grosso modo à la multi) le supporte.

Il faut le vérifier sur le forum officiel !

**Comment by rroblik** [comment]
Merci @gferry

J'ai le Note 3 en main (sortie delà boîte) et il ne me propose que le chinois / japonais et l'anglais ...
